services:
  app:
    image: prod-service:local
    container_name: ps-app
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:15
    container_name: ps-psql
    environment:
      - POSTGRES_DB=Lab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./data:/var/lib/postgresql/data