version: '3.8'

volumes:
  Labwork:

services:
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/Lab'
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: Lab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - Labwork:/var/lib/postgresql/data
    ports:
      - "5432:5432"