spring.application.name=Spring-Labs

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://db:5432/railway}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:YHVsDPHTmsbICDpxwwMxrJYVCJjQxCRG}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${PORT:8080}

logging.level.root=INFO
logging.level.com.springlabs=DEBUG
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/