spring.application.name=Spring-Labs

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/Lab
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.root=INFO
logging.level.com.springlabs=DEBUG
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/
#spring.application.name=Spring-Labs
#
#spring.jpa.show-sql=${JPA_SHOW_SQL:true}
#spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
#spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:Lab}
#spring.datasource.username=${DB_USERNAME:postgres}
#spring.datasource.password=${DB_PASSWORD:root}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#logging.level.root=INFO
#logging.level.com.springlabs=DEBUG
#
#spring.mvc.static-path-pattern=/**
#spring.web.resources.static-locations=classpath:/static/